# pesawat/data.py

FLIGHTS_DUMMY = [
    {
        "id": 1,
        "from_city": "Jakarta",
        "from_code": "CGK",
        "to_city": "Singapore",
        "to_code": "SIN",
        "trip_type": "One way",
        "date": "2026-01-15",
        "time": "08:40",
        "badge_text": "Direct",
        "badge_color": "blue",
        "price": 1295000,
        "original_price": 1450000,
        "airline_name": "Garuda Indonesia",
        "airline_code": "GA",
        "flight_number": "824",
        "airline_logo": "img/maskapai/GI.png",
        "class": "Economy",
    },
    {
        "id": 2,
        "from_city": "Jakarta",
        "from_code": "CGK",
        "to_city": "Denpasar",
        "to_code": "DPS",
        "trip_type": "One way",
        "date": "2026-01-20",
        "time": "09:10",
        "badge_text": "Promo",
        "badge_color": "green",
        "price": 1050000,
        "original_price": 1200000,
        "airline_name": "Batik Air",
        "airline_code": "ID",
        "flight_number": "6504",
        "airline_logo": "img/maskapai/batik-air.png",
        "class": "Economy",
    },
    {
        "id": 3,
        "from_city": "Jakarta",
        "from_code": "CGK",
        "to_city": "Medan",
        "to_code": "KNO",
        "trip_type": "One way",
        "date": "2026-01-22",
        "time": "13:45",
        "badge_text": "Direct",
        "badge_color": "blue",
        "price": 1380000,
        "original_price": None,
        "airline_name": "Citilink",
        "airline_code": "QG",
        "flight_number": "942",
        "airline_logo": "img/maskapai/citilink.png",
        "class": "Economy",
    },
    {
        "id": 4,
        "from_city": "Surabaya",
        "from_code": "SUB",
        "to_city": "Jakarta",
        "to_code": "CGK",
        "trip_type": "One way",
        "date": "2026-01-18",
        "time": "19:30",
        "badge_text": "Paling Laris",
        "badge_color": "orange",
        "price": 980000,
        "original_price": None,
        "airline_name": "Lion Air",
        "airline_code": "JT",
        "flight_number": "690",
        "airline_logo": "img/maskapai/lion.png",
        "class": "Economy",
    },
    {
        "id": 5,
        "from_city": "Jakarta",
        "from_code": "CGK",
        "to_city": "Tokyo",
        "to_code": "HND",
        "trip_type": "One way",
        "date": "2026-02-05",
        "time": "06:15",
        "badge_text": "Transit 1x",
        "badge_color": "purple",
        "price": 7850000,
        "original_price": None,
        "airline_name": "All Nippon Airways",
        "airline_code": "NH",
        "flight_number": "856",
        "airline_logo": "img/maskapai/ana.png",
        "class": "Economy",
    },
    {
        "id": 6,
        "from_city": "Denpasar",
        "from_code": "DPS",
        "to_city": "Sydney",
        "to_code": "SYD",
        "trip_type": "One way",
        "date": "2026-02-12",
        "time": "22:10",
        "badge_text": "Direct",
        "badge_color": "blue",
        "price": 4950000,
        "original_price": None,
        "airline_name": "Jetstar",
        "airline_code": "JQ",
        "flight_number": "38",
        "airline_logo": "img/maskapai/jet.png",
        "class": "Economy",
    },
    # Business Class Flights
    {
        "id": 7,
        "from_city": "Jakarta",
        "from_code": "CGK",
        "to_city": "Singapore",
        "to_code": "SIN",
        "trip_type": "One way",
        "date": "2026-01-15",
        "time": "08:40",
        "badge_text": "Direct",
        "badge_color": "blue",
        "price": 3850000,
        "original_price": 4200000,
        "airline_name": "Garuda Indonesia",
        "airline_code": "GA",
        "flight_number": "824",
        "airline_logo": "img/maskapai/GI.png",
        "class": "Business",
    },
    {
        "id": 8,
        "from_city": "Jakarta",
        "from_code": "CGK",
        "to_city": "Denpasar",
        "to_code": "DPS",
        "trip_type": "One way",
        "date": "2026-01-20",
        "time": "09:10",
        "badge_text": "Promo",
        "badge_color": "green",
        "price": 2850000,
        "original_price": 3200000,
        "airline_name": "Batik Air",
        "airline_code": "ID",
        "flight_number": "6504",
        "airline_logo": "img/maskapai/batik-air.png",
        "class": "Business",
    },
    # First Class Flights
    {
        "id": 9,
        "from_city": "Jakarta",
        "from_code": "CGK",
        "to_city": "Singapore",
        "to_code": "SIN",
        "trip_type": "One way",
        "date": "2026-01-15",
        "time": "08:40",
        "badge_text": "Premium",
        "badge_color": "purple",
        "price": 8500000,
        "original_price": None,
        "airline_name": "Garuda Indonesia",
        "airline_code": "GA",
        "flight_number": "824",
        "airline_logo": "img/maskapai/GI.png",
        "class": "First",
    },
    {
        "id": 10,
        "from_city": "Jakarta",
        "from_code": "CGK",
        "to_city": "Tokyo",
        "to_code": "HND",
        "trip_type": "One way",
        "date": "2026-02-05",
        "time": "06:15",
        "badge_text": "Premium",
        "badge_color": "purple",
        "price": 18500000,
        "original_price": None,
        "airline_name": "All Nippon Airways",
        "airline_code": "NH",
        "flight_number": "856",
        "airline_logo": "img/maskapai/ana.png",
        "class": "First",
    },
]